goalsapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :goals
end

goalsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goalsapp/app/models/goals.rb
class Goal < ActiveRecord::Base
  validates :name, presence: true

    belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User
end

goalsapp/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

    has_many :goals,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Goal

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end

  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_token
  end
end

goalsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
helper_method :current_user, :logged_in?

def current_user
  @current_user ||= User.find_by(session_token: session[:session_token])
end

def logged_in?
  !!current_user
end

def login_user(user)
  @current_user = user
  session[:session_token] = user.reset_session_token!
end

def logout_user
  current_user.reset_session_token!
  @current_user = nil
  session[:session_token] = nil
end

private

def require_current_user!
  redirect_to new_user_url unless current_user
end

def require_no_current_user!
  redirect_to root_url if current_user
end
end

goalsapp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_current_user!

  def index
    @goals = current_user.goals
    render :index
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      flash.now[:notices] = ["Goal saved!"]
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(goal_params)
      flash.now[:notices] = ["Goal updated!"]
      redirect_to @goal
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    flash.now[:notices] = ["Goal deleted!"]
    redirect_to goals_url
  end

  private

  def goal_params
    params.require(:goals).permit(:name, :details, :privacy, :completed)
  end
end

goalsapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_current_user!, only: [:destroy]
  before_action :require_no_current_user!, only: [:new, :create]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])

    if @user
      login_user(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Wrong username and/or password!"]
      render :new
    end
  end

  def destroy
    logout_user
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goalsapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_current_user!, only: [:new, :create]

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find_by_id(params[:id])

    if @user
      render :show
    else
      flash[:errors] = ["User does not exist"]
      index
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(username: user_params[:username], password: user_params[:password])

    if @user.save
      render :show
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goalsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

goalsapp/app/views/goals/edit.html.erb
<h1>New goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">
  <input type="hidden" name="_method" value="patch">

  <label for="name">Name: </label>
  <input type="text" name="goals[name]" value="<%= @goal.name %>">
  <br>

  <label for="details">Details: </label>
  <textarea name="goals[details]" rows="8" cols="80"><%= @goal.details %></textarea>
  <br>

  <label for="privacy">Private: </label>
  <input type="checkbox" name="goals[privacy]" value="<%= true %>" <%= @goal.privacy ? "checked" : ""%>>
  <br>

  <label for="completed">Completed: </label>
  <input type="checkbox" name="goals[completed]" value="<%= true %>" <%= @goal.completed ? "checked" : ""%>>
  <br>

  <input type="submit" value="Submit">
</form>

<%= link_to "Back to goal", goal_url(@goal), method: :get %>

goalsapp/app/views/goals/index.html.erb
<h1><%= current_user.username %> goals</h1>

<ul>
  <% current_user.goals.each do |goal| %>
    <li>
      <%= link_to goal.name, goal_url(goal), method: :get%>
      <%= link_to "Edit goal", edit_goal_url(goal), method: :get %>
    </li>
  <% end %>
</ul>

<%= link_to "Add goal", new_goal_url, method: :get %>

goalsapp/app/views/goals/new.html.erb
<h1>New goal</h1>

<form action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="name">Name: </label>
  <input type="text" name="goals[name]" value="">
  <br>

  <label for="details">Details: </label>
  <textarea name="goals[details]" rows="8" cols="80"></textarea>
  <br>

  <label for="privacy">Private: </label>
  <input type="checkbox" name="goals[privacy]" value="<%= true %>">
  <br>

  <label for="completed">Completed: </label>
  <input type="checkbox" name="goals[completed]" value="<%= true %>">
  <br>

  <input type="submit" value="Submit">
</form>

goalsapp/app/views/goals/show.html.erb
<h1><%= @goal.name %></h1>

<p><%= @goal.details %></p>

<%= link_to "Back to user", user_url(@goal.user_id), method: :get %>

goalsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goalsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <% if logged_in? %>
        <%= link_to "Log out", session_url, method: :delete %>
      <% else %>
        <%= link_to "Log in", new_session_url, method: :get %>
        <%= link_to "Sign up", new_user_url, method: :get %>
      <% end %>
    <%= yield %>
  </body>
</html>

goalsapp/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_url(user), method: :get %></li>
  <% end %>
</ul>

goalsapp/app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="username">Username: </label>
  <input type="text" name="user[username]" value="">
  <br>

  <label for="password">Password: </label>
  <input type="text" name="user[password]" value="">
  <br>

  <input type="submit" value="Submit">
</form>

goalsapp/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h3><%= link_to "Goals", goals_url, method: :get %></h3>